# Uncomment this line to define a global platform for your project
platform :ios
# Uncomment this line if you're using Swift
use_frameworks!

pod 'YJTableViewFactory', :git => 'https://github.com/937447974/YJTableViewFactory.git', :branch => ‘developer’

target 'TestSwift' do

end

