# Uncomment this line to define a global platform for your project
platform :ios, '6.0'
# Uncomment this line if you're using Swift
# use_frameworks!

pod 'YJCocoa/Foundation'
pod 'YJCocoa/System'

target 'YJTableViewFactory' do

end

target 'YJTableViewFactoryTests' do

end

target 'YJTableViewFactoryUITests' do

end

